function damp.map:setCustomColors()

	local r,g,b
	damp.log:debug("Setting color environment")

	-- Must remap mud-specified IDs to be in non-ANSI ranges (0-15),
	-- otherwise colors won't function correctly
	for k,v in pairs(gmcp.room.sectors.sectors) do
		damp.map.terrain[v.name] = v.id+16
	end

	--display(damp.map.terrain)

	-- Roads --
	r,g,b = unpack(color_table.DarkGoldenrod)
	setCustomEnvColor(damp.map.terrain["road_eastwest"], r,g,b, 255)
	r,g,b = unpack(color_table.DarkGoldenrod)
	setCustomEnvColor(damp.map.terrain["road"], r,g,b, 255)
	r,g,b = unpack(color_table.SaddleBrown)
	setCustomEnvColor(damp.map.terrain["bridge"], r,g,b, 255)
	r,g,b = unpack(color_table.burlywood)
	setCustomEnvColor(damp.map.terrain["road_crossroads"], r,g,b, 255)
	r,g,b = unpack(color_table.burlywood)
	setCustomEnvColor(damp.map.terrain["crossroad_nw"], r,g,b, 255)
	r,g,b = unpack(color_table.burlywood)
	setCustomEnvColor(damp.map.terrain["crossroad_se"], r,g,b, 255)
	r,g,b = unpack(color_table.burlywood)
	setCustomEnvColor(damp.map.terrain["crossroad_ews"], r,g,b, 255)
	r,g,b = unpack(color_table.DarkGoldenrod)
	setCustomEnvColor(damp.map.terrain["smallroad"], r,g,b, 255)
	r,g,b = unpack(color_table.DarkGoldenrod)
	setCustomEnvColor(damp.map.terrain["smallroad_ew"], r,g,b, 255)
	r,g,b = unpack(color_table.tan)
	setCustomEnvColor(damp.map.terrain["trail_ew"], r,g,b, 255)

	-- Misc --
	r,g,b = unpack(color_table.light_gray)
	setCustomEnvColor(damp.map.terrain["inside"], r,g,b, 255)
	r,g,b = unpack(color_table.LightCoral)
	setCustomEnvColor(damp.map.terrain["city"], r,g,b, 255)
	r,g,b = unpack(color_table.slate_grey)
	setCustomEnvColor(damp.map.terrain["unused"], r,g,b, 255)
	r,g,b = unpack(color_table.maroon )
	setCustomEnvColor(damp.map.terrain["Mudschool"], r,g,b, 255)
	r,g,b = unpack(color_table.dim_gray)
	setCustomEnvColor(damp.map.terrain["areaexit"], r,g,b, 255)
	r,g,b = unpack(color_table.plum)
	setCustomEnvColor(damp.map.terrain["castle"], r,g,b, 255)
	r,g,b = unpack(color_table.light_pink )
	setCustomEnvColor(damp.map.terrain["pillar"], r,g,b, 255)
	r,g,b = unpack(color_table.medium_purple)
	setCustomEnvColor(damp.map.terrain["temple"], r,g,b, 255)
	r,g,b = unpack(color_table.orange)
	setCustomEnvColor(damp.map.terrain["shop"], r,g,b, 255)
	r,g,b = unpack(color_table.red)
	setCustomEnvColor(damp.map.terrain["clanexit"], r,g,b, 255)
	r,g,b = unpack(color_table.dim_gray)
	setCustomEnvColor(damp.map.terrain["chessblack"], r,g,b, 255)
	r,g,b = unpack(color_table.white)
	setCustomEnvColor(damp.map.terrain["chesswhite"], r,g,b, 255)
	r,g,b = unpack(color_table.yellow_green )
	setCustomEnvColor(damp.map.terrain["lottery"], r,g,b, 255)
	r,g,b = unpack(color_table.yellow)
	setCustomEnvColor(damp.map.terrain["alley"], r,g,b, 255)
	r,g,b = unpack(color_table.linen)
	setCustomEnvColor(damp.map.terrain["office"], r,g,b, 255)
	r,g,b = unpack(color_table.DodgerBlue)
	setCustomEnvColor(damp.map.terrain["electric"], r,g,b, 255)
	r,g,b = unpack(color_table.DarkSlateBlue)
	setCustomEnvColor(damp.map.terrain["well"], r,g,b, 255)
	r,g,b = unpack(color_table.maroon)
	setCustomEnvColor(damp.map.terrain["bloodyhall"], r,g,b, 255)
	r,g,b = unpack(color_table.firebrick)
	setCustomEnvColor(damp.map.terrain["bloodyroom"], r,g,b, 255)
	r,g,b = unpack(color_table.MediumOrchid)
	setCustomEnvColor(damp.map.terrain["palace_room"], r,g,b, 255)
	r,g,b = unpack(color_table.SaddleBrown)
	setCustomEnvColor(damp.map.terrain["ship"], r,g,b, 255)
	r,g,b = unpack(color_table.LightGoldenrod)
	setCustomEnvColor(damp.map.terrain["hut"], r,g,b, 255)
	r,g,b = unpack(color_table.red)
	setCustomEnvColor(damp.map.terrain["redcarpet"], r,g,b, 255)
	r,g,b = unpack(color_table.DarkSlateGray)
	setCustomEnvColor(damp.map.terrain["city_underground"], r,g,b, 255)
	r,g,b = unpack(color_table.LightGoldenrod)
	setCustomEnvColor(damp.map.terrain["cabin"], r,g,b, 255)
	r,g,b = unpack(color_table.slate_grey)
	setCustomEnvColor(damp.map.terrain["hallway"], r,g,b, 255)
	r,g,b = unpack(color_table.dim_gray)
	setCustomEnvColor(damp.map.terrain["stairs"], r,g,b, 255)
	r,g,b = unpack(color_table.magenta )
	setCustomEnvColor(damp.map.terrain["aylorcity"], r,g,b, 255)
	r,g,b = unpack(color_table.aquamarine)
	setCustomEnvColor(damp.map.terrain["ruins"], r,g,b, 255)

	r,g,b = unpack(color_table.LightGrey)
	setCustomEnvColor(damp.map.terrain["graveyard"], r,g,b, 255)
	r,g,b = unpack(color_table.LightSlateGrey)
	setCustomEnvColor(damp.map.terrain["crypt"], r,g,b, 255)

	-- Weather/Environment --
	r,g,b = unpack(color_table.alice_blue)
	setCustomEnvColor(damp.map.terrain["mist"], r,g,b, 255)
	r,g,b = unpack(color_table.snow)
	setCustomEnvColor(damp.map.terrain["snow"], r,g,b, 255)
	r,g,b = unpack(color_table.slate_grey)
	setCustomEnvColor(damp.map.terrain["dark"], r,g,b, 255)
	r,g,b = unpack(color_table.mint_cream)
	setCustomEnvColor(damp.map.terrain["air"], r,g,b, 255)
	r,g,b = unpack(color_table.slate_grey)
	setCustomEnvColor(damp.map.terrain["moon"], r,g,b, 255)
	r,g,b = unpack(color_table.light_grey)
	setCustomEnvColor(damp.map.terrain["tornado"], r,g,b, 255)
	r,g,b = unpack(color_table.DarkKhaki)
	setCustomEnvColor(damp.map.terrain["dustdevil"], r,g,b, 255)
	r,g,b = unpack(color_table.white_smoke)
	setCustomEnvColor(damp.map.terrain["wind1"], r,g,b, 255)
	r,g,b = unpack(color_table.alice_blue)
	setCustomEnvColor(damp.map.terrain["wind2"], r,g,b, 255)
	r,g,b = unpack(color_table.steel_blue)
	setCustomEnvColor(damp.map.terrain["lightning"], r,g,b, 255)
	r,g,b = unpack(color_table.cyan)
	setCustomEnvColor(damp.map.terrain["rain"], r,g,b, 255)
	r,g,b = unpack(color_table.gold)
	setCustomEnvColor(damp.map.terrain["sun"], r,g,b, 255)
	r,g,b = unpack(color_table.snow)
	setCustomEnvColor(damp.map.terrain["cloud1"], r,g,b, 255)
	r,g,b = unpack(color_table.light_grey)
	setCustomEnvColor(damp.map.terrain["cloud2"], r,g,b, 255)
	r,g,b = unpack(color_table.gray)
	setCustomEnvColor(damp.map.terrain["cloud3"], r,g,b, 255)
	r,g,b = unpack(color_table.DeepPink)
	setCustomEnvColor(damp.map.terrain["rainbow"], r,g,b, 255)

	-- Outdoors --

	r,g,b = unpack(color_table.papaya_whip)
	setCustomEnvColor(damp.map.terrain["plain"], r,g,b, 255)
	r,g,b = unpack(color_table.yellow_green)
	setCustomEnvColor(damp.map.terrain["field"], r,g,b, 255)
	r,g,b = unpack(color_table.LawnGreen)
	setCustomEnvColor(damp.map.terrain["field2"], r,g,b, 255)
	r,g,b = unpack(color_table.yellow_green)
	setCustomEnvColor(damp.map.terrain["field3"], r,g,b, 255)
	r,g,b = unpack(color_table.green)
	setCustomEnvColor(damp.map.terrain["field4"], r,g,b, 255)
	r,g,b = unpack(color_table.dark_sea_green)
	setCustomEnvColor(damp.map.terrain["dead_field"], r,g,b, 255)
	r,g,b = unpack(color_table.bisque)
	setCustomEnvColor(damp.map.terrain["ashen_field"], r,g,b, 255)
	r,g,b = unpack(color_table.ForestGreen)
	setCustomEnvColor(damp.map.terrain["forest"], r,g,b, 255)
	r,g,b = unpack(color_table.OliveDrab)
	setCustomEnvColor(damp.map.terrain["dead_forest"], r,g,b, 255)
	r,g,b = unpack(color_table.MediumSpringGreen)
	setCustomEnvColor(damp.map.terrain["hills"], r,g,b, 255)
	r,g,b = unpack(color_table.RosyBrown)
	setCustomEnvColor(damp.map.terrain["mountain"], r,g,b, 255)
	r,g,b = unpack(color_table.thistle)
	setCustomEnvColor(damp.map.terrain["mountain_cyan"], r,g,b, 255)
	r,g,b = unpack(color_table.moccasin)
	setCustomEnvColor(damp.map.terrain["desert"], r,g,b, 255)
	r,g,b = unpack(color_table.sandy_brown)
	setCustomEnvColor(damp.map.terrain["quicksand"], r,g,b, 255)
	r,g,b = unpack(color_table.DarkSlateGray)
	setCustomEnvColor(damp.map.terrain["underground"], r,g,b, 255)
	r,g,b = unpack(color_table.firebrick)
	setCustomEnvColor(damp.map.terrain["volcano"], r,g,b, 255)
	r,g,b = unpack(color_table.dark_orange)
	setCustomEnvColor(damp.map.terrain["cave"], r,g,b, 255)
	r,g,b = unpack(color_table.maroon)
	setCustomEnvColor(damp.map.terrain["fiery_cave"], r,g,b, 255)
	r,g,b = unpack(color_table.purple)
	setCustomEnvColor(damp.map.terrain["dungeon"], r,g,b, 255)
	r,g,b = unpack(color_table.LightGoldenrod)
	setCustomEnvColor(damp.map.terrain["beach"], r,g,b, 255)
	r,g,b = unpack(color_table.pale_goldenrod)
	setCustomEnvColor(damp.map.terrain["shore"], r,g,b, 255)
	r,g,b = unpack(color_table.green)
	setCustomEnvColor(damp.map.terrain["jungle"], r,g,b, 255)
	r,g,b = unpack(color_table.OliveDrab)
	setCustomEnvColor(damp.map.terrain["dead_jungle"], r,g,b, 255)
	r,g,b = unpack(color_table.OliveDrab)
	setCustomEnvColor(damp.map.terrain["swamp"], r,g,b, 255)
	r,g,b = unpack(color_table.light_grey)
	setCustomEnvColor(damp.map.terrain["rocks"], r,g,b, 255)

	r,g,b = unpack(color_table.LightCyan)
	setCustomEnvColor(damp.map.terrain["ice"], r,g,b, 255)
	r,g,b = unpack(color_table.light_blue)
	setCustomEnvColor(damp.map.terrain["insideice"], r,g,b, 255)
	r,g,b = unpack(color_table.turquoise)
	setCustomEnvColor(damp.map.terrain["icemount"], r,g,b, 255)
	r,g,b = unpack(color_table.pale_turquoise)
	setCustomEnvColor(damp.map.terrain["icehills"], r,g,b, 255)

	r,g,b = unpack(color_table.DarkOrchid)
	setCustomEnvColor(damp.map.terrain["flowers1"], r,g,b, 255)
	r,g,b = unpack(color_table.MediumPurple)
	setCustomEnvColor(damp.map.terrain["flowers2"], r,g,b, 255)

	-- Water --
	r,g,b = unpack(color_table.cornflower_blue)
	setCustomEnvColor(damp.map.terrain["waterswim"], r,g,b, 255)
	r,g,b = unpack(color_table.medium_slate_blue)
	setCustomEnvColor(damp.map.terrain["waternoswim"], r,g,b, 255)
	r,g,b = unpack(color_table.deep_sky_blue)
	setCustomEnvColor(damp.map.terrain["ocean"], r,g,b, 255)
	r,g,b = unpack(color_table.dodger_blue)
	setCustomEnvColor(damp.map.terrain["ocean2"], r,g,b, 255)
	r,g,b = unpack(color_table.medium_blue)
	setCustomEnvColor(damp.map.terrain["ocean3"], r,g,b, 255)
	r,g,b = unpack(color_table.midnight_blue)
	setCustomEnvColor(damp.map.terrain["ocean4"], r,g,b, 255)
	r,g,b = unpack(color_table.NavyBlue)
	setCustomEnvColor(damp.map.terrain["underwater"], r,g,b, 255)
	r,g,b = unpack(color_table.medium_aquamarine)
	setCustomEnvColor(damp.map.terrain["river"], r,g,b, 255)
	r,g,b = unpack(color_table.cornflower_blue)
	setCustomEnvColor(damp.map.terrain["afountain"], r,g,b, 255)
	r,g,b = unpack(color_table.cornflower_blue)
	setCustomEnvColor(damp.map.terrain["fountain"], r,g,b, 255)
	r,g,b = unpack(color_table.purple)
	setCustomEnvColor(damp.map.terrain["chaos_sea"], r,g,b, 255)

	-- Library --
	r,g,b = unpack(color_table.OldLace)
	setCustomEnvColor(damp.map.terrain["archive"], r,g,b, 255)
	r,g,b = unpack(color_table.DarkKhaki)
	setCustomEnvColor(damp.map.terrain["bookshelves"], r,g,b, 255)
	r,g,b = unpack(color_table.DarkKhaki)
	setCustomEnvColor(damp.map.terrain["bookshelves_ns"], r,g,b, 255)

	-- Hell --
	r,g,b = unpack(color_table.maroon)
	setCustomEnvColor(damp.map.terrain["hellinside"], r,g,b, 255)
	r,g,b = unpack(color_table.violet_red)
	setCustomEnvColor(damp.map.terrain["hellhall"], r,g,b, 255)
	r,g,b = unpack(color_table.firebrick)
	setCustomEnvColor(damp.map.terrain["hellfountain"], r,g,b, 255)
	r,g,b = unpack(color_table.red)
	setCustomEnvColor(damp.map.terrain["hell1"], r,g,b, 255)
	r,g,b = unpack(color_table.tomato)
	setCustomEnvColor(damp.map.terrain["hell2"], r,g,b, 255)
	r,g,b = unpack(color_table.OrangeRed)
	setCustomEnvColor(damp.map.terrain["hell3"], r,g,b, 255)
	r,g,b = unpack(color_table.coral)
	setCustomEnvColor(damp.map.terrain["hell4"], r,g,b, 255)

	-- Space --
	r,g,b = unpack(color_table.light_grey)
	setCustomEnvColor(damp.map.terrain["space1"], r,g,b, 255)
	r,g,b = unpack(color_table.gray)
	setCustomEnvColor(damp.map.terrain["space2"], r,g,b, 255)
	r,g,b = unpack(color_table.dim_gray)
	setCustomEnvColor(damp.map.terrain["space3"], r,g,b, 255)
	r,g,b = unpack(color_table.dark_slate_grey)
	setCustomEnvColor(damp.map.terrain["space4"], r,g,b, 255)

end
