function daagar.map:setCustomColors()

local r,g,b
daagar.log:debug("Setting color environment")

-- Must remap mud-specified IDs to be in non-ANSI ranges (0-15),
-- otherwise colors won't function correctly
for k,v in pairs(gmcp.room.sectors.sectors) do
daagar.map.terrain[v.name] = v.id+16
end

display(daagar.map.terrain)

-- Roads --
r,g,b = unpack(color_table.DarkGoldenrod)
setCustomEnvColor(daagar.map.terrain["road_eastwest"], r,g,b, 255)
r,g,b = unpack(color_table.DarkGoldenrod)
setCustomEnvColor(daagar.map.terrain["road"], r,g,b, 255)
r,g,b = unpack(color_table.SaddleBrown)
setCustomEnvColor(daagar.map.terrain["bridge"], r,g,b, 255)
r,g,b = unpack(color_table.burlywood)
setCustomEnvColor(daagar.map.terrain["road_crossroads"], r,g,b, 255)
r,g,b = unpack(color_table.burlywood)
setCustomEnvColor(daagar.map.terrain["crossroad_nw"], r,g,b, 255)
r,g,b = unpack(color_table.burlywood)
setCustomEnvColor(daagar.map.terrain["crossroad_se"], r,g,b, 255)
r,g,b = unpack(color_table.burlywood)
setCustomEnvColor(daagar.map.terrain["crossroad_ews"], r,g,b, 255)
r,g,b = unpack(color_table.DarkGoldenrod)
setCustomEnvColor(daagar.map.terrain["smallroad"], r,g,b, 255)
r,g,b = unpack(color_table.DarkGoldenrod)
setCustomEnvColor(daagar.map.terrain["smallroad_ew"], r,g,b, 255)
r,g,b = unpack(color_table.tan)
setCustomEnvColor(daagar.map.terrain["trail_ew"], r,g,b, 255)

-- Misc --
r,g,b = unpack(color_table.light_gray)
setCustomEnvColor(daagar.map.terrain["inside"], r,g,b, 255)
r,g,b = unpack(color_table.LightCoral)
setCustomEnvColor(daagar.map.terrain["city"], r,g,b, 255)
r,g,b = unpack(color_table.slate_grey)
setCustomEnvColor(daagar.map.terrain["unused"], r,g,b, 255)
r,g,b = unpack(color_table.maroon )
setCustomEnvColor(daagar.map.terrain["Mudschool"], r,g,b, 255)
r,g,b = unpack(color_table.dim_gray)
setCustomEnvColor(daagar.map.terrain["areaexit"], r,g,b, 255)
r,g,b = unpack(color_table.plum)
setCustomEnvColor(daagar.map.terrain["castle"], r,g,b, 255)
r,g,b = unpack(color_table.light_pink )
setCustomEnvColor(daagar.map.terrain["pillar"], r,g,b, 255)
r,g,b = unpack(color_table.medium_purple)
setCustomEnvColor(daagar.map.terrain["temple"], r,g,b, 255)
r,g,b = unpack(color_table.orange)
setCustomEnvColor(daagar.map.terrain["shop"], r,g,b, 255)
r,g,b = unpack(color_table.red)
setCustomEnvColor(daagar.map.terrain["clanexit"], r,g,b, 255)
r,g,b = unpack(color_table.dim_gray)
setCustomEnvColor(daagar.map.terrain["chessblack"], r,g,b, 255)
r,g,b = unpack(color_table.white)
setCustomEnvColor(daagar.map.terrain["chesswhite"], r,g,b, 255)
r,g,b = unpack(color_table.yellow_green )
setCustomEnvColor(daagar.map.terrain["lottery"], r,g,b, 255)
r,g,b = unpack(color_table.yellow)
setCustomEnvColor(daagar.map.terrain["alley"], r,g,b, 255)
r,g,b = unpack(color_table.linen)
setCustomEnvColor(daagar.map.terrain["office"], r,g,b, 255)
r,g,b = unpack(color_table.DodgerBlue)
setCustomEnvColor(daagar.map.terrain["electric"], r,g,b, 255)
r,g,b = unpack(color_table.DarkSlateBlue)
setCustomEnvColor(daagar.map.terrain["well"], r,g,b, 255)
r,g,b = unpack(color_table.maroon)
setCustomEnvColor(daagar.map.terrain["bloodyhall"], r,g,b, 255)
r,g,b = unpack(color_table.firebrick)
setCustomEnvColor(daagar.map.terrain["bloodyroom"], r,g,b, 255)
r,g,b = unpack(color_table.MediumOrchid)
setCustomEnvColor(daagar.map.terrain["palace_room"], r,g,b, 255)
r,g,b = unpack(color_table.SaddleBrown)
setCustomEnvColor(daagar.map.terrain["ship"], r,g,b, 255)
r,g,b = unpack(color_table.LightGoldenrod)
setCustomEnvColor(daagar.map.terrain["hut"], r,g,b, 255)
r,g,b = unpack(color_table.red)
setCustomEnvColor(daagar.map.terrain["redcarpet"], r,g,b, 255)
r,g,b = unpack(color_table.DarkSlateGray)
setCustomEnvColor(daagar.map.terrain["city_underground"], r,g,b, 255)
r,g,b = unpack(color_table.LightGoldenrod)
setCustomEnvColor(daagar.map.terrain["cabin"], r,g,b, 255)
r,g,b = unpack(color_table.slate_grey)
setCustomEnvColor(daagar.map.terrain["hallway"], r,g,b, 255)
r,g,b = unpack(color_table.dim_gray)
setCustomEnvColor(daagar.map.terrain["stairs"], r,g,b, 255)
r,g,b = unpack(color_table.magenta )
setCustomEnvColor(daagar.map.terrain["aylorcity"], r,g,b, 255)
r,g,b = unpack(color_table.aquamarine)
setCustomEnvColor(daagar.map.terrain["ruins"], r,g,b, 255)

r,g,b = unpack(color_table.LightGrey)
setCustomEnvColor(daagar.map.terrain["graveyard"], r,g,b, 255)
r,g,b = unpack(color_table.LightSlateGrey)
setCustomEnvColor(daagar.map.terrain["crypt"], r,g,b, 255)

-- Weather/Environment --
r,g,b = unpack(color_table.alice_blue)
setCustomEnvColor(daagar.map.terrain["mist"], r,g,b, 255)
r,g,b = unpack(color_table.snow)
setCustomEnvColor(daagar.map.terrain["snow"], r,g,b, 255)
r,g,b = unpack(color_table.slate_grey)
setCustomEnvColor(daagar.map.terrain["dark"], r,g,b, 255)
r,g,b = unpack(color_table.mint_cream)
setCustomEnvColor(daagar.map.terrain["air"], r,g,b, 255)
r,g,b = unpack(color_table.slate_grey)
setCustomEnvColor(daagar.map.terrain["moon"], r,g,b, 255)
r,g,b = unpack(color_table.light_grey)
setCustomEnvColor(daagar.map.terrain["tornado"], r,g,b, 255)
r,g,b = unpack(color_table.DarkKhaki)
setCustomEnvColor(daagar.map.terrain["dustdevil"], r,g,b, 255)
r,g,b = unpack(color_table.white_smoke)
setCustomEnvColor(daagar.map.terrain["wind1"], r,g,b, 255)
r,g,b = unpack(color_table.alice_blue)
setCustomEnvColor(daagar.map.terrain["wind2"], r,g,b, 255)
r,g,b = unpack(color_table.steel_blue)
setCustomEnvColor(daagar.map.terrain["lightning"], r,g,b, 255)
r,g,b = unpack(color_table.cyan)
setCustomEnvColor(daagar.map.terrain["rain"], r,g,b, 255)
r,g,b = unpack(color_table.gold)
setCustomEnvColor(daagar.map.terrain["sun"], r,g,b, 255)
r,g,b = unpack(color_table.snow)
setCustomEnvColor(daagar.map.terrain["cloud1"], r,g,b, 255)
r,g,b = unpack(color_table.light_grey)
setCustomEnvColor(daagar.map.terrain["cloud2"], r,g,b, 255)
r,g,b = unpack(color_table.gray)
setCustomEnvColor(daagar.map.terrain["cloud3"], r,g,b, 255)
r,g,b = unpack(color_table.DeepPink)
setCustomEnvColor(daagar.map.terrain["rainbow"], r,g,b, 255)

-- Outdoors --

r,g,b = unpack(color_table.papaya_whip)
setCustomEnvColor(daagar.map.terrain["plain"], r,g,b, 255)
r,g,b = unpack(color_table.yellow_green)
setCustomEnvColor(daagar.map.terrain["field"], r,g,b, 255)
r,g,b = unpack(color_table.LawnGreen)
setCustomEnvColor(daagar.map.terrain["field2"], r,g,b, 255)
r,g,b = unpack(color_table.yellow_green)
setCustomEnvColor(daagar.map.terrain["field3"], r,g,b, 255)
r,g,b = unpack(color_table.green)
setCustomEnvColor(daagar.map.terrain["field4"], r,g,b, 255)
r,g,b = unpack(color_table.dark_sea_green)
setCustomEnvColor(daagar.map.terrain["dead_field"], r,g,b, 255)
r,g,b = unpack(color_table.bisque)
setCustomEnvColor(daagar.map.terrain["ashen_field"], r,g,b, 255)
r,g,b = unpack(color_table.ForestGreen)
setCustomEnvColor(daagar.map.terrain["forest"], r,g,b, 255)
r,g,b = unpack(color_table.OliveDrab)
setCustomEnvColor(daagar.map.terrain["dead_forest"], r,g,b, 255)
r,g,b = unpack(color_table.MediumSpringGreen)
setCustomEnvColor(daagar.map.terrain["hills"], r,g,b, 255)
r,g,b = unpack(color_table.RosyBrown)
setCustomEnvColor(daagar.map.terrain["mountain"], r,g,b, 255)
r,g,b = unpack(color_table.thistle)
setCustomEnvColor(daagar.map.terrain["mountain_cyan"], r,g,b, 255)
r,g,b = unpack(color_table.moccasin)
setCustomEnvColor(daagar.map.terrain["desert"], r,g,b, 255)
r,g,b = unpack(color_table.sandy_brown)
setCustomEnvColor(daagar.map.terrain["quicksand"], r,g,b, 255)
r,g,b = unpack(color_table.DarkSlateGray)
setCustomEnvColor(daagar.map.terrain["underground"], r,g,b, 255)
r,g,b = unpack(color_table.firebrick)
setCustomEnvColor(daagar.map.terrain["volcano"], r,g,b, 255)
r,g,b = unpack(color_table.dark_orange)
setCustomEnvColor(daagar.map.terrain["cave"], r,g,b, 255)
r,g,b = unpack(color_table.maroon)
setCustomEnvColor(daagar.map.terrain["fiery_cave"], r,g,b, 255)
r,g,b = unpack(color_table.purple)
setCustomEnvColor(daagar.map.terrain["dungeon"], r,g,b, 255)
r,g,b = unpack(color_table.LightGoldenrod)
setCustomEnvColor(daagar.map.terrain["beach"], r,g,b, 255)
r,g,b = unpack(color_table.pale_goldenrod)
setCustomEnvColor(daagar.map.terrain["shore"], r,g,b, 255)
r,g,b = unpack(color_table.green)
setCustomEnvColor(daagar.map.terrain["jungle"], r,g,b, 255)
r,g,b = unpack(color_table.OliveDrab)
setCustomEnvColor(daagar.map.terrain["dead_jungle"], r,g,b, 255)
r,g,b = unpack(color_table.OliveDrab)
setCustomEnvColor(daagar.map.terrain["swamp"], r,g,b, 255)
r,g,b = unpack(color_table.light_grey)
setCustomEnvColor(daagar.map.terrain["rocks"], r,g,b, 255)

r,g,b = unpack(color_table.LightCyan)
setCustomEnvColor(daagar.map.terrain["ice"], r,g,b, 255)
r,g,b = unpack(color_table.light_blue)
setCustomEnvColor(daagar.map.terrain["insideice"], r,g,b, 255)
r,g,b = unpack(color_table.turquoise)
setCustomEnvColor(daagar.map.terrain["icemount"], r,g,b, 255)
r,g,b = unpack(color_table.pale_turquoise)
setCustomEnvColor(daagar.map.terrain["icehills"], r,g,b, 255)

r,g,b = unpack(color_table.DarkOrchid)
setCustomEnvColor(daagar.map.terrain["flowers1"], r,g,b, 255)
r,g,b = unpack(color_table.MediumPurple)
setCustomEnvColor(daagar.map.terrain["flowers2"], r,g,b, 255)

-- Water --
r,g,b = unpack(color_table.cornflower_blue)
setCustomEnvColor(daagar.map.terrain["waterswim"], r,g,b, 255)
r,g,b = unpack(color_table.medium_slate_blue)
setCustomEnvColor(daagar.map.terrain["waternoswim"], r,g,b, 255)
r,g,b = unpack(color_table.deep_sky_blue)
setCustomEnvColor(daagar.map.terrain["ocean"], r,g,b, 255)
r,g,b = unpack(color_table.dodger_blue)
setCustomEnvColor(daagar.map.terrain["ocean2"], r,g,b, 255)
r,g,b = unpack(color_table.medium_blue)
setCustomEnvColor(daagar.map.terrain["ocean3"], r,g,b, 255)
r,g,b = unpack(color_table.midnight_blue)
setCustomEnvColor(daagar.map.terrain["ocean4"], r,g,b, 255)
r,g,b = unpack(color_table.NavyBlue)
setCustomEnvColor(daagar.map.terrain["underwater"], r,g,b, 255)
r,g,b = unpack(color_table.medium_aquamarine)
setCustomEnvColor(daagar.map.terrain["river"], r,g,b, 255)
r,g,b = unpack(color_table.cornflower_blue)
setCustomEnvColor(daagar.map.terrain["afountain"], r,g,b, 255)
r,g,b = unpack(color_table.cornflower_blue)
setCustomEnvColor(daagar.map.terrain["fountain"], r,g,b, 255)
r,g,b = unpack(color_table.purple)
setCustomEnvColor(daagar.map.terrain["chaos_sea"], r,g,b, 255)

-- Library --
r,g,b = unpack(color_table.OldLace)
setCustomEnvColor(daagar.map.terrain["archive"], r,g,b, 255)
r,g,b = unpack(color_table.DarkKhaki)
setCustomEnvColor(daagar.map.terrain["bookshelves"], r,g,b, 255)
r,g,b = unpack(color_table.DarkKhaki)
setCustomEnvColor(daagar.map.terrain["bookshelves_ns"], r,g,b, 255)

-- Hell --
r,g,b = unpack(color_table.maroon)
setCustomEnvColor(daagar.map.terrain["hellinside"], r,g,b, 255)
r,g,b = unpack(color_table.violet_red)
setCustomEnvColor(daagar.map.terrain["hellhall"], r,g,b, 255)
r,g,b = unpack(color_table.firebrick)
setCustomEnvColor(daagar.map.terrain["hellfountain"], r,g,b, 255)
r,g,b = unpack(color_table.red)
setCustomEnvColor(daagar.map.terrain["hell1"], r,g,b, 255)
r,g,b = unpack(color_table.tomato)
setCustomEnvColor(daagar.map.terrain["hell2"], r,g,b, 255)
r,g,b = unpack(color_table.OrangeRed)
setCustomEnvColor(daagar.map.terrain["hell3"], r,g,b, 255)
r,g,b = unpack(color_table.coral)
setCustomEnvColor(daagar.map.terrain["hell4"], r,g,b, 255)
 
-- Space --
r,g,b = unpack(color_table.light_grey)
setCustomEnvColor(daagar.map.terrain["space1"], r,g,b, 255)
r,g,b = unpack(color_table.gray)
setCustomEnvColor(daagar.map.terrain["space2"], r,g,b, 255)
r,g,b = unpack(color_table.dim_gray)
setCustomEnvColor(daagar.map.terrain["space3"], r,g,b, 255)
r,g,b = unpack(color_table.dark_slate_grey)
setCustomEnvColor(daagar.map.terrain["space4"], r,g,b, 255)

end
